openapi: 3.0.0
info:
  title: Synapse Template Integration CLI
  description: CLI contracts for CLAUDE.md template integration functionality
  version: 1.0.0

paths:
  /cli/init:
    post:
      summary: Enhanced synapse init with template integration
      description: Initialize Synapse with template-based CLAUDE.md integration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                project_name:
                  type: string
                  description: Override detected project name
                workflow_dir:
                  type: string
                  default: ".synapse"
                  description: Custom workflow directory
                force:
                  type: boolean
                  default: false
                  description: Overwrite existing configuration
                template_integration:
                  type: boolean
                  default: true
                  description: Enable CLAUDE.md template integration
                preserve_existing:
                  type: boolean
                  default: true
                  description: Preserve existing CLAUDE.md content
              required:
                - project_name
      responses:
        '200':
          description: Successful initialization with template integration
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  project_name:
                    type: string
                  workflow_dir:
                    type: string
                  template_integration:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      backup_created:
                        type: boolean
                      user_content_preserved:
                        type: boolean
                      conflicts_detected:
                        type: array
                        items:
                          type: string
                  commands_installed:
                    type: array
                    items:
                      type: string
                  warnings:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid parameters or configuration conflict
        '409':
          description: Unresolvable command conflicts detected
        '500':
          description: Template integration failed

  /cli/template:
    post:
      summary: Manual template integration
      description: Manually trigger CLAUDE.md template integration
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                force_backup:
                  type: boolean
                  default: true
                  description: Force creation of backup file
                preserve_slots:
                  type: array
                  items:
                    type: string
                  description: Specific content slots to preserve
                template_version:
                  type: string
                  description: Template version to use
      responses:
        '200':
          description: Template integration completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  backup_file:
                    type: string
                  preserved_slots:
                    type: array
                    items:
                      type: string
                  template_version:
                    type: string
        '400':
          description: Invalid template parameters
        '409':
          description: Template integration conflicts

  /cli/commands/install:
    post:
      summary: Install Synapse slash commands
      description: Install or update Synapse slash commands with conflict detection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commands:
                  type: array
                  items:
                    type: string
                  description: Specific commands to install (default: all)
                conflict_resolution:
                  type: string
                  enum: ["prefix", "warn", "skip", "interactive"]
                  default: "prefix"
                  description: How to resolve command conflicts
                force_install:
                  type: boolean
                  default: false
                  description: Install despite conflicts
      responses:
        '200':
          description: Commands installed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  installed_commands:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        file_path:
                          type: string
                        conflicts_resolved:
                          type: boolean
                  conflicts:
                    type: array
                    items:
                      type: object
                      properties:
                        command_name:
                          type: string
                        conflict_type:
                          type: string
                        resolution:
                          type: string
        '409':
          description: Unresolvable command conflicts
        '500':
          description: Command installation failed

  /cli/conflicts/detect:
    get:
      summary: Detect command conflicts
      description: Scan for conflicts between Synapse and existing commands
      responses:
        '200':
          description: Conflict detection completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  conflicts_found:
                    type: boolean
                  conflicts:
                    type: array
                    items:
                      type: object
                      properties:
                        command_name:
                          type: string
                        existing_source:
                          type: string
                        synapse_command:
                          type: string
                        conflict_type:
                          type: string
                        suggested_resolution:
                          type: string
                  scan_date:
                    type: string
                    format: date-time

components:
  schemas:
    ConflictInfo:
      type: object
      properties:
        command_name:
          type: string
        existing_source:
          type: string
        synapse_command:
          type: string
        conflict_type:
          type: string
          enum: ["name_collision", "functionality_overlap", "prefix_conflict"]
        resolution:
          type: string
          enum: ["use_prefix", "warn_user", "skip_command", "user_choice"]
        detected_date:
          type: string
          format: date-time

    TemplateConfig:
      type: object
      properties:
        template_version:
          type: string
        user_content_slots:
          type: object
          additionalProperties:
            type: string
        backup_created:
          type: boolean
        integration_date:
          type: string
          format: date-time
        original_file_hash:
          type: string

    SlashCommand:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
        agent_target:
          type: string
          enum: ["DEV", "AUDITOR", "DISPATCHER"]
        command_file_path:
          type: string
        is_synapse_managed:
          type: boolean
        installation_date:
          type: string
          format: date-time