openapi: 3.0.0
info:
  title: Template Integration Service API
  description: Internal API contracts for CLAUDE.md template integration service
  version: 1.0.0

paths:
  /template/analyze:
    post:
      summary: Analyze existing CLAUDE.md file
      description: Analyze existing CLAUDE.md to extract user content and identify integration strategy
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                file_path:
                  type: string
                  description: Path to existing CLAUDE.md file
                template_version:
                  type: string
                  description: Target template version
              required:
                - file_path
      responses:
        '200':
          description: Analysis completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  file_exists:
                    type: boolean
                  content_sections:
                    type: array
                    items:
                      type: object
                      properties:
                        section_type:
                          type: string
                        content:
                          type: string
                        line_start:
                          type: integer
                        line_end:
                          type: integer
                  user_content_slots:
                    type: object
                    additionalProperties:
                      type: string
                  integration_strategy:
                    type: string
                    enum: ["template_replacement", "slot_based", "hybrid"]
                  backup_required:
                    type: boolean
        '404':
          description: CLAUDE.md file not found
        '400':
          description: Invalid file format or template version

  /template/integrate:
    post:
      summary: Perform template integration
      description: Integrate user content into Synapse CLAUDE.md template
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                source_file:
                  type: string
                  description: Path to source CLAUDE.md file
                template_config:
                  $ref: '#/components/schemas/TemplateConfig'
                integration_strategy:
                  type: string
                  enum: ["template_replacement", "slot_based", "hybrid"]
                create_backup:
                  type: boolean
                  default: true
              required:
                - source_file
                - template_config
      responses:
        '200':
          description: Integration completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  output_file:
                    type: string
                  backup_file:
                    type: string
                  preserved_content:
                    type: object
                    additionalProperties:
                      type: string
                  warnings:
                    type: array
                    items:
                      type: string
        '400':
          description: Invalid integration parameters
        '500':
          description: Integration failed

  /template/validate:
    post:
      summary: Validate template integration
      description: Validate that template integration preserved content correctly
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                integrated_file:
                  type: string
                  description: Path to integrated CLAUDE.md file
                original_content:
                  type: object
                  additionalProperties:
                    type: string
                  description: Original user content for comparison
                template_version:
                  type: string
              required:
                - integrated_file
                - original_content
      responses:
        '200':
          description: Validation completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_valid:
                    type: boolean
                  validation_errors:
                    type: array
                    items:
                      type: object
                      properties:
                        error_type:
                          type: string
                        message:
                          type: string
                        location:
                          type: string
                  content_integrity:
                    type: object
                    properties:
                      slots_preserved:
                        type: integer
                      slots_lost:
                        type: integer
                      content_modifications:
                        type: array
                        items:
                          type: string

  /commands/register:
    post:
      summary: Register slash commands
      description: Register Synapse slash commands with conflict detection
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commands:
                  type: array
                  items:
                    $ref: '#/components/schemas/SlashCommand'
                command_dir:
                  type: string
                  description: Directory to install command files
                conflict_resolution:
                  type: string
                  enum: ["prefix", "warn", "skip", "interactive"]
                  default: "prefix"
              required:
                - commands
                - command_dir
      responses:
        '200':
          description: Commands registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  registered_commands:
                    type: array
                    items:
                      type: string
                  conflicts_detected:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConflictInfo'
                  files_created:
                    type: array
                    items:
                      type: string
        '409':
          description: Unresolvable command conflicts
        '500':
          description: Command registration failed

  /commands/detect-conflicts:
    post:
      summary: Detect command conflicts
      description: Detect conflicts between proposed commands and existing ones
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                proposed_commands:
                  type: array
                  items:
                    type: string
                command_dir:
                  type: string
                  description: Directory to scan for existing commands
              required:
                - proposed_commands
                - command_dir
      responses:
        '200':
          description: Conflict detection completed
          content:
            application/json:
              schema:
                type: object
                properties:
                  conflicts:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConflictInfo'
                  conflict_summary:
                    type: object
                    properties:
                      total_conflicts:
                        type: integer
                      name_collisions:
                        type: integer
                      functionality_overlaps:
                        type: integer
                      resolvable_conflicts:
                        type: integer

components:
  schemas:
    TemplateConfig:
      type: object
      properties:
        template_version:
          type: string
        user_content_slots:
          type: object
          additionalProperties:
            type: string
        backup_created:
          type: boolean
        integration_date:
          type: string
          format: date-time
        original_file_hash:
          type: string
      required:
        - template_version
        - user_content_slots

    SlashCommand:
      type: object
      properties:
        name:
          type: string
          pattern: '^/synapse:[a-z]+$'
        description:
          type: string
        agent_target:
          type: string
          enum: ["DEV", "AUDITOR", "DISPATCHER"]
        command_template:
          type: string
          description: Template content for command file
        is_synapse_managed:
          type: boolean
          default: true
      required:
        - name
        - description
        - agent_target
        - command_template

    ConflictInfo:
      type: object
      properties:
        command_name:
          type: string
        existing_source:
          type: string
        synapse_command:
          type: string
        conflict_type:
          type: string
          enum: ["name_collision", "functionality_overlap", "prefix_conflict"]
        resolution:
          type: string
          enum: ["use_prefix", "warn_user", "skip_command", "user_choice"]
        detected_date:
          type: string
          format: date-time
        is_resolvable:
          type: boolean
      required:
        - command_name
        - existing_source
        - synapse_command
        - conflict_type

    ContentSlot:
      type: object
      properties:
        slot_name:
          type: string
          pattern: '^[a-z_]+$'
        content:
          type: string
        is_preserved:
          type: boolean
        original_location:
          type: string
        slot_type:
          type: string
          enum: ["CONTEXT", "INSTRUCTIONS", "CUSTOM", "METADATA"]
      required:
        - slot_name
        - content
        - slot_type

    IntegrationStrategy:
      type: object
      properties:
        strategy_type:
          type: string
          enum: ["template_replacement", "slot_based", "hybrid"]
        content_mapping:
          type: object
          additionalProperties:
            type: string
        preservation_rules:
          type: array
          items:
            type: object
            properties:
              rule_type:
                type: string
              pattern:
                type: string
              action:
                type: string
        migration_required:
          type: boolean
      required:
        - strategy_type
        - content_mapping