"""Models module for Synapse agent workflow system."""

from .command import (
    AgentType,
    CommandInfo,
    CommandRegistry,
    ConflictInfo,
    ConflictResolution,
    ConflictType,
    SlashCommand,
)
from .project import AgentConfig, InitResult, ProjectConfig, ValidationResult
from .task import (
    AgentTemplate,
    Finding,
    Subtask,
    SubtaskStatus,
    Task,
    TaskLogEntry,
    TaskStatus,
    TaskType,
    VerificationReport,
    VerificationStatus,
    WorkflowState,
    WorkflowStatus,
)
from .template import (
    ContentSlot,
    IntegrationStrategy,
    IntegrationType,
    PreservationRule,
    SlotType,
    TemplateConfig,
)

__all__ = [
    "AgentConfig",
    "AgentTemplate",
    "AgentType",
    "CommandInfo",
    "CommandRegistry",
    "ConflictInfo",
    "ConflictResolution",
    "ConflictType",
    "ContentSlot",
    "Finding",
    "InitResult",
    "IntegrationStrategy",
    "IntegrationType",
    "PreservationRule",
    "ProjectConfig",
    "SlashCommand",
    "SlotType",
    "Subtask",
    "SubtaskStatus",
    "Task",
    "TaskLogEntry",
    "TaskStatus",
    "TaskType",
    "TemplateConfig",
    "ValidationResult",
    "VerificationReport",
    "VerificationStatus",
    "WorkflowState",
    "WorkflowStatus",
]
