openapi: 3.0.0
info:
  title: Synapse CLI Commands
  version: 1.0.0
  description: Simple CLI with only init command - all other functionality via Claude Code slash commands

# Only one CLI command: synapse init
paths:
  /cli/init:
    post:
      summary: Initialize project with Synapse workflow and Claude Code integration
      operationId: synapseInit
      parameters:
        - name: project-name
          in: query
          required: false
          schema:
            type: string
          description: Override detected project name
        - name: workflow-dir
          in: query
          required: false
          schema:
            type: string
            default: ".synapse"
          description: Custom workflow directory name
        - name: force
          in: query
          required: false
          schema:
            type: boolean
            default: false
          description: Overwrite existing Synapse configuration
      responses:
        '201':
          description: Project initialized successfully with Claude agents and slash commands
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitResult'
        '409':
          description: Project already initialized (use --force to overwrite)
        '400':
          description: Invalid project structure or parameters

  # All other functionality is handled by Claude Code slash commands:
  # /status - Show workflow status
  # /workflow - Manage workflow state
  # /validate - Validate configuration
  # /agent - Manage agents

components:
  schemas:
    InitResult:
      type: object
      required:
        - success
        - project_name
        - workflow_dir
        - agents_created
        - commands_created
      properties:
        success:
          type: boolean
        project_name:
          type: string
        workflow_dir:
          type: string
        agents_created:
          type: array
          items:
            type: string
          description: List of Claude agent files created
        commands_created:
          type: array
          items:
            type: string
          description: List of Claude slash command files created
        files_created:
          type: array
          items:
            type: string
          description: All files created during initialization
        warnings:
          type: array
          items:
            type: string
          description: Any warnings during initialization