#!/bin/bash
# UserPromptSubmit Hook - Active Tasks Management Reminder
# Reminds agent of mandatory workflow requirements on every user prompt

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "ACTIVE TASKS MANAGEMENT RULES (third_party_workflow.active_tasks)"
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "1. STARTING WORK:"
echo "   - SET active_tasks to task codes you're working on (e.g., [\"T001\", \"T002\"])"
echo "   - Example: active_tasks: [\"T001\", \"T002\", \"T003\"]"
echo ""
echo "2. DURING VERIFICATION:"
echo "   - Run ALL quality checks for each active task"
echo "   - Mark QA Status based on results:"
echo "     • [Passed] - All checks passed"
echo "     • [Failed - {reason}] - Include specific failure details"
echo "   - NEVER mark as [Passed] without actually running checks"
echo ""
echo "3. AFTER VERIFICATION WITH FAILURES:"
echo "   - Present results to user with pass/fail breakdown"
echo "   - ASK: 'Would you like me to fix the failed tasks?'"
echo "   - If user says NO:"
echo "     → REMOVE passed tasks from active_tasks"
echo "     → KEEP failed tasks in active_tasks"
echo "     → Stop (hook allows stop with [Failed] status)"
echo "   - If user says YES:"
echo "     → KEEP failed tasks in active_tasks"
echo "     → Fix issues"
echo "     → SET QA Status back to [Not Started] (needs re-verification)"
echo "     → Re-run verification"
echo ""
echo "4. AFTER ALL TASKS PASS:"
echo "   - Generate completion report"
echo "   - CLEAR active_tasks to [] (empty array)"
echo "   - Stop (hook allows stop)"
echo ""
echo "5. CONTINUING WORK ON FAILED TASKS:"
echo "   - If you see active_tasks with [Failed] status:"
echo "     → User wants these fixed"
echo "     → Fix the issues"
echo "     → SET QA Status to [Not Started]"
echo "     → Verify again"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo "QA STATUS VALUES:"
echo "═══════════════════════════════════════════════════════════════"
echo "  [Not Started]          - Not verified (hook BLOCKS stop)"
echo "  [Passed] or [Complete] - Verified successfully (hook allows stop)"
echo "  [Failed - {reason}]    - Verified with failures (hook allows stop)"
echo ""
echo "═══════════════════════════════════════════════════════════════"
